### ISSUE TITLE
The plugin "object-assign" didn't export a Plugin instance

### ISSUE THREAD

**Issue by iambrandonn** [gaearon/react-dnd#279]
My webpack build using react-dnd version 1.1.4 today has suddenly started getting this error:

````
ERROR in ./~/react-dnd/~/dnd-core/lib/index.js
Module build failed: TypeError: The plugin "object-assign" didn't export a Plugin instance
    at PluginManager.validate (./node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (./node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (./node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (./node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (./node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (./node_modules/babel-loader/index.js:12:22)
    at ./node_modules/babel-loader/lib/fs-cache.js:140:16
    at ./node_modules/babel-loader/lib/fs-cache.js:27:23
    at fs.js:208:20
    at Object.oncomplete (fs.js:108:15)
````

Was new code release under the same version number???

**Comment by iambrandonn** [comment]
It appears that when the dependency dnd-core 1.2.0 was released this occurred.  If I pin it at 1.1.0 all is well again.

**Comment by gaearon** [comment]
You shouldn't compile `node_modules` with Babel. It looks like you're trying to process `dnd-core` with Babel a second time, which you shouldn't do.

**Comment by gaearon** [comment]
Your Babel loader configuration should have an `include` option so it only transforms your app:

```js
    loaders: [{
      test: /\.js$/,
      loader: 'babel',
      include: path.join(__dirname, 'src') // or wherever your source is
    }]
```

**Comment by iambrandonn** [comment]
That works.  Thanks!
